### ISSUE TITLE
healpix-cxx-config

### ISSUE THREAD

**Issue by HealthyPear** [conda-forge/healpix_cxx-feedstock#25]
### Comment:

Hi all,

I am trying to build a CMake-based project within a conda environment on macos in which HEALPix is one of the required dependencies.

I am not at all an expert of CMake, so I just went around the `src` folder of the project I am trying to build and found `vim ../src/cmake/Packages/HEALPix.cmake`.

In this file (which I think it's not produced at build time, it should be really how the developers expect the package to be configured, am I right?) I can see the following (I just show the beginning, let me know if you need to see more),

```
################################################################################
  2 # Module to find HEALPix-cxx                                                   #
  3 #                                                                              #
  4 #   HEALPIX_FOUND                                                              #
  5 #   HEALPIX_LIBRARIES                                                          #
  6 #   HEALPIX_INCLUDE_DIR                                                        #
  7 #   HEALPIX_BIN_DIR                                                            #
  8 #   HEALPIX_LIB_DIR                                                            #
  9 #   HEALPIX_CPPFLAGS                                                           #
 10 #   HEALPIX_LDFLAGS                                                            #
 11 ################################################################################
 12
 13 SET (HEALPix_FIND_QUIETLY TRUE)
 14 SET (HEALPix_FIND_REQUIRED FALSE)
 15
 16 IF (NOT HEALPIX_FOUND)
 17
 18   # Search user environment for healpix-cxx config script; then default paths
 19   FIND_PATH (HEALPIX_BIN_DIR healpix-cxx-config PATHS $ENV{HEALPIXROOT}/bin
 20     NO_DEFAULT_PATH)
 21   FIND_PATH (HEALPIX_BIN_DIR healpix-cxx-config)
```

On an Ubuntu machine, this package is built from source.
`HEALPIXROOT` is defined and under it the bin directory hosts the healpix-cxx-config executable.

On my macos (but I think it's general), conda places everything under `$CONDA_PREFIX/bin` where I cannot find such configurable.

Another difference is that on macos I cam trying to use healpix-cxx 3.80, while the ubuntu machine used 3.31.

Is this executable supposed to be there in my case?
Conda should already place all the headers and libraries in the default places, and I can see from the Cmake configuration that things like  FFTW3, CFITSIO, GSL, etc are found without having to do anything else, but HEALPIX it's not found even at the beginning.

**Comment by Areustle** [comment]
`healpix-cxx-config` is not an executable created by the Healpix package. It seems to be a [bash script](https://user-web.icecube.wisc.edu/~sybenzvi/software.php) written by one of the ICECube developers @sybenzvi . You can contact them to ask for additional information on its use.

The way I recommend including this healpix-cxx conda-forge package in a CMake project is to use the [built-in pkg-config features](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html?highlight=pkg_check_modules#command:pkg_check_modules) to locate the healpix_cxx libraries at the CMAKE generate step, and use the `PkgConfig::healpix_cxx` target to link the libraries into your local targets.

``` cmake
pkg_check_modules(healpix_cxx REQUIRED IMPORTED_TARGET GLOBAL healpix_cxx)

add_executable(healthypear healthypear.cpp)
target_link_libraries(healthypear PRIVATE PkgConfig::healpix_cxx)
```

Check out the https://github.com/fermi-lat/ScienceTools/blob/a3e72109d4467a75dae25bf56856cd70465ace28/CMakeLists.txt#L45 for a working example.

**Comment by HealthyPear** [comment]
The stuff in there seems quite general, than the lat line reads
`# Remaining details for the build
 24 INCLUDE (cmake/toplevel.cmake NO_POLICY_SCOPE)`

then  in `src/cmake/toplevel.cmake` at some point there is a `INCLUDE (HEALPix)` (which I think it's not working because I can't see at the beginning of the CMake configuration something like e.g. for the `fftw` package dependency

```
-- FFTW3 found
--   * includes: /Users/michele/Applications/mambaforge/envs/swgo_aerie_test/include
--   * libs:     /Users/michele/Applications/mambaforge/envs/swgo_aerie_test/lib/libfftw3.dylib
```

**Comment by Areustle** [comment]
> Could it be that the CMakeList file was written many years ago and it's not compatible with the version I am using?

I suspect that is right. Cmake version 2.8 is _very old_ and more modern versions of cmake have added a lot of additional features and paradigms to make using cmake more sane and enjoyable for developers and users. pkg_check_modules was added in version 3.1 and updated most recently in 3.18.

The kinds of syntax you're describing imply the obsolete form of cmake, so my prior recommendation is not going to help if you're not going to rewrite the cmake files of your tool.

As I see it you have two choices: 

- The easier option is to download and use the IceCube script. That may help you build your tool locally at least, just to get started.
- The harder option is to [learn](https://cliutils.gitlab.io/modern-cmake/) [cmake](https://cmake.org/cmake/help/latest/index.html) and rewrite your build files to
   - Use the pkg_check_modules import method
   - Use a different dependency location method along the lines of what the IceCube script is doing.
